shiny:
  image:
    repository: inseefrlab/shiny-app-template
    tag: "1.0.1"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: 
      - host: myshinyapp.lab.sspcloud.fr
        paths:
        - path: /
          pathType: Prefix
  s3:
    enabled: true
    existingSecret: myshinyapp-s3
  postgresql:
    enabled: true
    auth:
      username: myusername
      database: defaultdb
      existingSecret: myshinyapp-postgresql
    containerPorts:
      postgresql: 5432
    fullnameOverride: postgresql-db
    primary:
      persistence:
        size: 2Gi
